results = runtests({...
    'tensor_test.m', ...
    'tensor3_test.m', ...
    'tensor4_test.m', ...
    'tensor4Eye_test.m',...
    'tensor4Flatten_test.m',...
    'tensorHadamardProduct_test.m',...
    'tensorHadamardCollapsed_test.m'...
    });

table(results)