results = runtests({...
    'tensorHadamard_1_test.m', ...
    'tensorHadamard_2_test.m', ...
    'tensorHadamard_3_test.m', ...
    'tensorHadamard_4_test.m', ...
    'tensorHadamard_5_test.m', ...
    'tensor4Eye_test.m', ...
    });

table(results)